/*
 * This source file was generated by the Gradle 'init' task
 */
package generator.server;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        ServerLauncher classUnderTest = new ServerLauncher();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
