/*
 * This source file was generated by the Gradle 'init' task
 */
package tools.refinery.generator.server;




import org.eclipse.jetty.ee10.servlet.ServletContextHandler;
import org.eclipse.jetty.ee10.websocket.server.config.JettyWebSocketServletContainerInitializer;
import org.eclipse.jetty.server.Server;


public class ServerLauncher {
    public static void main(String[] args) throws Exception {
		// Create a Server with a ServerConnector listening on port 8080.
		Server server = new Server(8080);

		// Create a ServletContextHandler with the given context path.
		ServletContextHandler handler = new ServletContextHandler(ServletContextHandler.SESSIONS);
		handler.setContextPath("/");
		server.setHandler(handler);

		// Ensure that JavaxWebSocketServletContainerInitializer is initialized,
		// to set up the ServerContainer for this web application context.
		JettyWebSocketServletContainerInitializer.configure(handler, null);


		// Add a WebSocket-initializer Servlet to register WebSocket endpoints.
		handler.addServlet(GeneratorServerInitServlet.class, "/");

		// Starting the Server will start the ServletContextHandler.
		System.out.println("Starting server...");
		server.start();
    }
}
