services:
  web:
    image: ghcr.io/graphs4value/refinery
    ports:
      - "1312:1312"
    environment:
      REFINERY_GENERATOR_WS_HOST: "0.0.0.0"
      REFINERY_GENERATOR_WS_PORT: "1314"
    networks:
      - proxy-communication

  generator:
    image: ghcr.io/graphs4value/refinery-generator
    ports:
      - "1314:1314"
    environment:
      REFINERY_GENERATOR_WS_PORT: "1314"
    networks:
      - proxy-communication


networks:
  proxy-communication :
    name: proxy_network
    driver: bridge
