services:
  web:
    image: ghcr.io/graphs4value/refinery
    ports:
      - "1312:1312"
    environment:
      REFINERY_GENERATOR_WS_HOST: "localhost"
      REFINERY_GENERATOR_WS_PORT: "1314"
    network_mode: host

  generator:
    image: ghcr.io/graphs4value/refinery-generator
    ports:
      - "1314:1314"
    environment:
      REFINERY_GENERATOR_WS_PORT: "1314"
    network_mode: host
